export const magicWords = [
  // existing magic words
  'Is Cryotherapy good for recovery?',
  'Best yoga exercises for beginners',
  'How to improve my posture',
  'Exercises to strengthen the core',
  'Recommended stretches for runners',
  'What should I eat after working out?',
  'How can I relieve stress and anxiety?',
  'Tips for better sleep',
  'Benefits of meditation',
  'Are protein shakes necessary?',
  'Importance of hydration',
  'Effective HIIT workouts',
  'Signs of overtraining',
  'Dealing with muscle soreness',
  'Types of massages and their benefits',
  'Cardio exercises for weight loss',
  'Calisthenics for muscle building',
  'How long should I rest between sets?',
  'Using foam rollers for recovery',
  'What is active recovery?',
  'Most effective ab exercises',
  'Flexibility training tips',
  'Preventing workout injuries',
  'Breathing techniques for relaxation',
  'Benefits of a balanced diet',
  'Staying motivated while exercising',
  'Understanding macronutrients',
  'The role of vitamins and minerals',
  'The importance of warm-ups',
  'Cool down exercises for after a workout',
  'How to set fitness goals',
  'Techniques to improve running speed',
  'Understanding body composition',
  'Optimizing workout recovery',
  'Cross-training for improved performance',
  'The impact of mindfulness on wellbeing',
  'How to boost your immune system naturally',
  'Creating a workout routine for your goals',
  'When to use ice or heat for muscle pain',
  'Walking vs. running: which is better?',
  'Tracking progress using fitness apps',
  'Wearable fitness gadgets: are they worth it?',
  'Strength training for endurance athletes',
  'The best Pilates moves for core strength',
  'Can a sauna help with muscle recovery?',
  'How to balance cardio and strength training',
  'Understanding body fat percentage',
  'The role of antioxidants in recovery',
  'How to train for a marathon',
  'The benefits of swimming for fitness',
  'Finding the right exercise routine for you',
  'Home workout essentials',
  'Creating a balanced exercise routine',
  'Overcoming workout plateaus',
  'The mental health benefits of exercise'
  ]